### ISSUE TITLE
Compilation error: function full_path/1 undefined

### ISSUE THREAD

**Issue by ghost** [whatyouhide/plug_heartbeat#2]
I included Trot in a project of mine, and plug_heartbeat comes as a dependency. Then I've got this error at compile time:

```
== Compilation error on file lib/plug_heartbeat.ex ==
** (CompileError) lib/plug_heartbeat.ex:48: function full_path/1 undefined
    (stdlib) lists.erl:1337: :lists.foreach/2
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6

==> plug_heartbeat
could not compile dependency plug_heartbeat, mix compile failed. You can recompile this dependency with `mix deps.compile plug_heartbeat` or update it with `mix deps.update plug_heartbeat`
```

Which is weird because if I git clone & mix compile the repository, it compiles perfectly well.

**Comment by whatyouhide** [comment]
Hey @Annwenn, thanks for reporting! I updated plug_heartbeat to v0.2.0, which fixes the problem, and opened an issue on trot to notify of the update. Let me know if that'll fix things!

**Comment by hexedpackets** [comment]
@whatyouhide Thanks for jumping on this so quickly and letting me know about your fix!

@Annwenn I just pushed up v0.5.3 of Trot which uses v0.2.0 of plug_heartbeat, let me know if you have any problems with it.
